#!/bin/sh
################################################################################
##
## Copyright 2012 - 2016, Göteborg Bit Factory.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included
## in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##
## http://www.opensource.org/licenses/mit-license.php
##
################################################################################

# There is one line per updated ref on STDIN:
#   <oldrev> <newrev> <refname>
#   aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
while read LINE
do
  # Extract info from the line.
  IFS=" "
  set -- $LINE

  FROM=$1
  TO=$2
  BRANCH=$3
  BRANCH=${BRANCH##refs/heads/}
  BRANCH=${BRANCH:-HEAD}

  # Obtain a list of commits for the given range.
  git rev-list ${FROM}..${TO} | while read COMMIT
  do
    AUTHOR=`git log -1 --format="%an" $COMMIT`

    TIMESTAMP=`git log -1 --format="%at" $COMMIT`

    EVENT=`mktemp`

    cat <<EOF >$EVENT
branch: $BRANCH
commit: $COMMIT
author: $AUTHOR
timestamp: $TIMESTAMP

EOF

    central post changes $EVENT
    rm $EVENT
  done
done

