#!/bin/sh
################################################################################
##
## Copyright 2012 - 2016, Göteborg Bit Factory.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included
## in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##
## http://www.opensource.org/licenses/mit-license.php
##
################################################################################

REPOSITORY=$(git config --get remote.origin.url)
if [[ -z $REPOSITORY ]]
then
  REPOSITORY=$PWD
fi
PROJECT=$(basename $REPOSITORY)

BRANCH=$(git symbolic-ref -q HEAD)
BRANCH=${BRANCH##refs/heads/}
BRANCH=${BRANCH:-HEAD}

COMMIT=`git rev-parse HEAD`

AUTHOR=`git log -1 --format="%an" HEAD`

TIMESTAMP=`git log -1 --format="%at" HEAD`

EVENT=`mktemp`

cat <<EOF >$EVENT
project: $PROJECT
branch: $BRANCH
commit: $COMMIT
author: $AUTHOR
timestamp: $TIMESTAMP

EOF

central post changes $EVENT
rm $EVENT

exit $?

