#!/bin/sh
################################################################################
##
## Copyright 2012 - 2016, Göteborg Bit Factory.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included
## in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##
## http://www.opensource.org/licenses/mit-license.php
##
################################################################################

EVENT=$1

# TODO Read $EVENT file, and central config, in order to create one build event
#      for each required platform.
echo prepare_builds $EVENT

# TODO Given that $EVENT contains this:
#      project
#      branch
#      commit
#      author
#      timestamp

# TODO Given that central .flodrc contains this:
#      project.task.description     'Example repository for demo purposes'
#      project.task.ignore          'README*,*.md'
#      project.task.platforms       'debian7,freebsd'
#      project.task.dependencies    'git,c++,gnutls,uuid,python'
#      project.task.scm             'git'
#      project.task.repository      'https://git.tasktools.org/scm/tm/task.git'
#      project.task.prebuild        'cmake .'
#      project.task.build           'make'
#      project.task.test            'make test'
#      scm.git.obtain               'git clone ${project.${event.project}.repository}'
#      scm.git.branch               'git checkout ${event.branch}'
#      scm.git.commit               'git reset —hard ${event.commit}'
#      platform.debian7.description 'Debian 7 wheezy'
#      platform.debian7.pkg.git     'git'
#      platform.debian7.pkg.c++     'build-essential'
#      platform.debian7.pkg.gnutls  'gnutls-dev'
#      platform.debian7.pkg.uuid    'uuid-dev'
#      platform.debian7.pkg.python  'python'
#      platform.freebsd.description 'FreeBSD 9'
#      platform.freebsd.pkg.git     'git'
#      platform.freebsd.pkg.c++     'build-essential'
#      platform.freebsd.pkg.gnutls  'gnutls-dev'
#      platform.freebsd.pkg.uuid    ''
#      platform.freebsd.pkg.python  'python'

# TODO Compose these two events:
#        branch:                2.5.1
#        commit:                39cc00ce9d34b1253b41ca9dd555106ea98eb9c2
#        author:                Paul Beckingham <paul@beckingham.net>
#        timestamp:             Wed Jan 27 13:39:45 2016 -0500
#        project.scm:           git
#        project.repository:    https://git.tasktools.org/scm/tm/task.git
#        project.prebuild:      cmake .
#        project.build:         make
#        project.test:          make test
#        scm.obtain:            git clone https://git.tasktools.org/scm/tm/task.git
#        scm.branch:            git checkout 2.5.1
#        scm.commit:            git reset —hard 39cc00ce9d34b1253b41ca9dd555106ea98eb9c2
#        platform.description:  Debian 7 wheezy
#        platform.dependencies: git,build-essential,gnutls-dev,uuid-dev,python

#        project:               task
#        branch:                2.5.1
#        commit:                39cc00ce9d34b1253b41ca9dd555106ea98eb9c2
#        author:                Paul Beckingham <paul@beckingham.net>
#        timestamp:             Wed Jan 27 13:39:45 2016 -0500
#        project.scm:           git
#        project.repository:    https://git.tasktools.org/scm/tm/task.git
#        project.prebuild:      cmake .
#        project.build:         make
#        project.test:          make test
#        scm.obtain:            git clone https://git.tasktools.org/scm/tm/task.git
#        scm.branch:            git checkout 2.5.1
#        scm.commit:            git reset —hard 39cc00ce9d34b1253b41ca9dd555106ea98eb9c2
#        platform.description:  FreeBSD 9
#        platform.dependencies: git,build-essential,gnutls-dev,python

