#!/bin/sh
################################################################################
##
## Copyright 2012 - 2016, Göteborg Bit Factory.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included
## in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##
## http://www.opensource.org/licenses/mit-license.php
##
################################################################################

EVENT=$1

# TODO Read $EVENT file, and central config, in order to create one build event
#      for each required platform.
echo prepare_builds $EVENT

# TODO Read project   from $EVENT --> $PROJECT
# TODO Read branch    from $EVENT
# TODO Read commit    from $EVENT
# TODO Read author    from $EVENT
# TODO Read timestamp from $EVENT

# TODO Read project.task.repository from .flodrc
# TODO Read project.task.prebuild   from .flodrc
# TODO Read project.task.build      from .flodrc
# TODO Read project.task.test       from .flodrc

# TODO Read project.$PROJECT.scm from .flodrc --> $SCM
# TODO Given project.$PROJECT.scm read scm.$SCM.obtain from .flodrc
# TODO Given project.$PROJECT.scm read scm.$SCM.branch from .flodrc
# TODO Given project.$PROJECT.scm read scm.$SCM.commit from .flodrc

# TODO Read project.$PROJECT.platforms from .flodrc --> $PLATFORMS
# TODO Read project.$PROJECT.dependencies from .flodrc --> $DEPENDENCIES
# TODO For each PLATFORM in $PLATFORMS
  # TODO Map $DEPENDENCIES for $PLATFORM
  # TODO mktemp --> $BUILD_EVENT
  # TODO Compose build event > $BUILD_EVENT
  # TODO central post build-$PLATFORM $BUILD_EVENT
  # TODO rm $BUILD_EVENT

